name: tagpr
on:
  push:
    branches: [main]
  pull_request:
    types: [labeled]
permissions:
  contents: write
  pull-requests: write
  issues: write
jobs:
  tagpr:
    runs-on: [self-hosted, Linux, X64, ci]
    steps:
      - uses: actions/checkout@v4
      - id: tagpr
      - uses: Songmu/tagpr@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
